### ISSUE TITLE
List formatting not functional

### ISSUE THREAD

**Issue by gzip-pa** [educaide/ckeditor-dev#10]
Steps to reproduce:
Log into PA account and navigate to the Play Area
Select a question bank
Click "Edit" on a problem 
Select some lines of text, then select something from the list tool in the toolbar, such as numbers of bullets.
Result:
No changes to the selected text apparent either within the editor window or in the problem thumbnail after it has been saved. The html code visible in the "information" window for the problem shows no list markup.

Previously existing Multiple choice lists, which in the Production version of the editor are highlighted in pink with the correct answer marked in green, show no such formatting in the editor on staging. The right-click context menu applied to those lists display options for marking the correct answer and for "multiple choice advanced", but these have no affect when selected.

**Comment by Reinmar** [comment]
That's most likely due to missing contents stylesheet. You need to use the [`config.contentsCss](http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-contentsCss) option.

**Comment by Reinmar** [comment]
This will also be related to #12.

**Comment by gzip-pa** [comment]
Fixed
