### ISSUE TITLE
404 error upon uploading an image

### ISSUE THREAD

**Issue by gzip-pa** [educaide/ckeditor-dev#14]
Steps to reproduce:
Log into PA account and navigate to the Play Area
Select a question bank
Click "Edit" on a problem or write a new one.
Select the Image icon from the toolbar
Select "Upload" and attempt to upload an image.

Result: you see the generic PA 404 page "The page you were looking for doesn't exist.". Clicking "Cancel" and relaunching the image editor shows that the images was, in fact, uploaded.

http://www.staging.problem-attic.com/figures.json Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.staging.problem-attic.com/account/figures/31751?style=thumb Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.staging.problem-attic.com/javascripts/ckeditor/_source/plugins/easimage/dialog.html#user_images/success Failed to load resource: the server responded with a status of 404 (Not Found)
ckeditor.js:46800 Uncaught TypeError: Cannot set property 'value' of null
http://www.staging.problem-attic.com/javascripts/ckeditor/_source/plugins/easimage/dialog.html#user_images/success Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by Reinmar** [comment]
The figures.json gives 404 even on http://www.problem-attic.com/

I don't see other 404 errors.

I do however see the this:

```
Uncaught ReferenceError: inch_width is not definedcreateImage @ ckeditor.js:46765CKEDITOR.plugins.add.init.CKEDITOR.dialog.addIframe.onOk @ ckeditor.js:46822(anonymous function) @ ckeditor.js:32760listenerFirer @ ckeditor.js:460CKEDITOR.event.fire @ ckeditor.js:606CKEDITOR.tools.extend.okButton.CKEDITOR.tools.extend.onClick @ ckeditor.js:34037(anonymous function) @ ckeditor.js:31842listenerFirer @ ckeditor.js:460CKEDITOR.event.fire @ ckeditor.js:606CKEDITOR.ui.dialog.button.CKEDITOR.tools.extend.click @ ckeditor.js:31794(anonymous function) @ ckeditor.js:31426listenerFirer @ ckeditor.js:460CKEDITOR.event.fire @ ckeditor.js:606CKEDITOR.dom.domObject.getNativeListener @ ckeditor.js:3120
```

I fixed this error with git:d052d6f. As the 404 errors are something I cannot resolve myself I'm assigning "invalid" label.

**Comment by gcortright** [comment]
@Reinmar You're correct re: the 404 + `inch_width`. `inch_width` was/is the culprit.

**Comment by gcortright** [comment]
@gzip-pa please retest

**Comment by gzip-pa** [comment]
Fixed
