### ISSUE TITLE
Cannot add image to problem using image editor

### ISSUE THREAD

**Issue by gzip-pa** [educaide/ckeditor-dev#15]
Steps to reproduce:
Log into PA account and navigate to the Play Area
Select a question bank
Click "Edit" on a problem or write a new one.
Select the Image icon from the toolbar.

If you  have previously uploaded images to the account you'll see some images. Select an imagesand click "OK".

Nothing happens when you click OK.

**Comment by Reinmar** [comment]
Should be fixed by the change I made in #14.

**Comment by gcortright** [comment]
@gzip-pa please retest

**Comment by gzip-pa** [comment]
Yup. Fixed
