### ISSUE TITLE
"Insert Specials" Blanks and Misc not working correctly

### ISSUE THREAD

**Issue by gzip-pa** [educaide/ckeditor-dev#16]
Steps to reproduce:
Log into PA account and navigate to the Play Area
Select a question bank
Click "Edit" on a problem or write a new one.
Select "Blanks and Misc" from the Σ dropdown menu. 
Select something, like Line, and click OK.
RESULT:
The text "bl" is entered into your document no matter what you select. No line is visible.
Missing css?

**Comment by Reinmar** [comment]
Yes, it seems to be the same problem as in #10. Plus it will be related to #12 as well.

**Comment by gcortright** [comment]
@gzip-pa please retest

**Comment by gzip-pa** [comment]
Yup - Fixed
