### ISSUE TITLE
Word Style formatting not visible in editor

### ISSUE THREAD

**Issue by gzip-pa** [educaide/ckeditor-dev#18]
Steps to reproduce:
Log into PA account and navigate to the Play Area
Select a question bank
Click "Edit" on a problem or write a new one.
Select some text an apply a "Word Style" such as Emphasis (italic) or Vocab (underline)

Result:
No change in styling is apparent in the editor. If the problem is saved the formatting will be visible in the problem thumbnail (eas-class="word-emph" is appliedto the span). 
If the problem is subsequently reopened for editing the Word Style changes will be undone, per issue #12 .

**Comment by gcortright** [comment]
@gzip-pa please retest

**Comment by gzip-pa** [comment]
Fixed
