### ISSUE TITLE
"Redo" button not working

### ISSUE THREAD

**Issue by gzip-pa** [educaide/ckeditor-dev#19]
Steps to reproduce:
Log into PA account and navigate to the Play Area
Select a question bank
Click "Edit" on a problem or write a new one.
Make some changes to existing text or other element, for example, delete a word from a line of text.
Click "undo" button on the editor toolbar, or use ^z on your keyboard - your text re-appears.
Result:
At this point the adjacent "Redo" button should be enabled, but it is gray and un-clickable. The ^y keyboard command should also function as a "redo" but it is also not functioning.

**Comment by Reinmar** [comment]
I reproduced the issue on the staging server and confirmed that this is a regression (it worked before). I cannot however reproduce this locally what makes debugging harder.

**Comment by Reinmar** [comment]
OK, that was tough, because I could not test it locally, but I found it:

```
      stem_editor.on('dataReady',function() {
        if (true || !Prototype.Browser.IE) {  // IE can eat a bowl of d###
          stem_editor.resetUndo();
          stem_editor.resetDirty();
        }
      });
```

No wonder that we cannot redo if on `dataReady` (which is fired also on undo/redo) the whole stack is reset :D.

I guess that what you wanted was to reset the stack after data is loaded into the editor and that can be done in a callback of `editor.setData()`:

```
editor.setData( newData, {
    callback: function() {
        editor.resetUndo();
        editor.resetDirty();
    }
} );
```

**Comment by gcortright** [comment]
@Reinmar ah, interesting. It is a very old snippet, from well before my time ;) I wonder that it worked at all with CK3!. I have a branch of changes to our app code for use with the new editor. I'll get the change working and checked in there, thanks!!

**Comment by gcortright** [comment]
@gzip-pa please retest

**Comment by gzip-pa** [comment]
yep -- fixed
