### ISSUE TITLE
Changes to problem are saved when editing is "Canceled"

### ISSUE THREAD

**Issue by gzip-pa** [educaide/ckeditor-dev#2]
Steps to reproduce:
Open a problem for editing
Click the "Cancel" button

Result: You will see a message at the top of the pages that says "Saving Changes"
If you had made any changes to text they will be saved at this stage (does not apply for editing Multiple choice answer and other elements that are currently broken).
Expected behavior: No changes are saved when you exit the editor using "Cancel". Instead you should see a, "Are you sure?" warning that none of your changes will be saved with "OK and "Cancel buttons. Changes should only be saved when you click "Save".

**Comment by Reinmar** [comment]
The same as here: https://github.com/educaide/ckeditor-dev/issues/1#issuecomment-129925819

**Comment by gzip-pa** [comment]
fixed
