### ISSUE TITLE
Problem Editor: Table Properties Layout/Position field too narrow to dislay all text in some browsers

### ISSUE THREAD

**Issue by gzip-pa** [educaide/ckeditor-dev#23]
_From @gzip-pa on June 24, 2015 17:52_

Edit a problem using Chrome 4.3 in Windows 7
Create a Table
in the Table Properties dialog, select "center" or "Indent"

Observe  that last letter of that word is truncated.
![table_properties](https://cloud.githubusercontent.com/assets/12751439/8337246/d92ba3de-1a5e-11e5-8ec5-b38ed53d121b.png)

Text appears as expected in Firefox.

_Copied from original issue: educaide/hachiko#444_

**Comment by patrickdavey** [comment]
fixed https://github.com/educaide/ckeditor/blob/05dbd4fae89bb946432bbc9db974c376900a3d46/_source/plugins/eastable/dialog.css#L89-L91 but need to know what to open the PR against.

**Comment by patrickdavey** [comment]
This doesn't seem to be an issue on the ckeditor4 branch. 

![screen shot 2015-09-15 at 11 48 01 am](https://cloud.githubusercontent.com/assets/549469/9864646/cd4acaae-5b9f-11e5-9d63-e33deb06b0c8.png)
