### ISSUE TITLE
Problem Editor: In IE 11, Lists are set at top of problem no matter what you do

### ISSUE THREAD

**Issue by gzip-pa** [educaide/ckeditor-dev#24]
_From @gzip-pa on June 26, 2015 18:21_

Create a new problem and enter a few separate lines of text.
Select a couple of lines of text at the bottom of the problem, excluding the top line of text.
Click the List icon in the toolbar and select Multiple Choice - or any other type of list.

Result:
The topmost line of text in the problem will be formatted as a list, not the text you selected.
It is also not possible to type anything above and outside of this list. The list can only exist at the top of the problem.

A similar misbehavior in marking the correct answer of a newly created MC list has been observed, where the correct answer will be placed at the top of the list rather than on the selected list item

Conclusion: Nobody should be using IE 11 with the Problem Editor in its current state. If these issues cannot be fixed we might display a warning to IE users recommending they use a different  browser.

Observed with IE version 11.0.9600.17843 on Windows 7

_Copied from original issue: educaide/hachiko#462_

**Comment by Reinmar** [comment]
WFM now on the staging server.
