### ISSUE TITLE
Problem Editor: Context menu for Parabox, "Remove Paragraph Box" doesn't work.

### ISSUE THREAD

**Issue by gzip-pa** [educaide/ckeditor-dev#25]
_From @gzip-pa on June 26, 2015 17:32_

Edit a problem.
Select a paragraph box.
Right click and select "Remove Paragraph Box" from the context menu. Nothing happens.

Paragraph boxes can only be removed by selecting surrounding areas and hitting 'delete'.

_Copied from original issue: educaide/hachiko#461_

**Comment by Reinmar** [comment]
That's because:

```
Uncaught ReferenceError: getEasBlockElem is not defineddeleteEasBlockElem @ ckeditor.js:48421parboxDelete @ ckeditor.js:48438CKEDITOR.plugins.add.init.editor.addCommand.exec @ ckeditor.js:48544exec @ ckeditor.js:10939CKEDITOR.tools.extend.execCommand @ ckeditor.js:16099CKEDITOR.menu.CKEDITOR.tools.createClass._.onClick @ ckeditor.js:42978CKEDITOR.tools.bind @ ckeditor.js:1919(anonymous function) @ ckeditor.js:43146(anonymous function) @ ckeditor.js:2005CKEDITOR.tools.callFunction @ ckeditor.js:2033onclick @ 88211:1
```

It does not work on the production server as well. This method isn't defined in this plugin, but I was able to find a similarly named method in easproperties so I'll copy it there.
