### ISSUE TITLE
Problem Editor: images and symbols in multiple choice block cannot be directly selected as correct answer

### ISSUE THREAD

**Issue by gzip-pa** [educaide/ckeditor-dev#27]
_From @gzip-pa on June 25, 2015 20:2_

Write or edit a problem that contains only math symbols, images or icons in the multiple choice block.
Select a different correct answer by directly right- clicking the icon or symbol.
Result:
The selected icon turns blue and will not accept the correct answer designation. An icon can on be selected as the correct answer only when you right-click the empty area to the right of the icon. This is not intuitive and could be a source of frustration to the user.

This question bank contains example of questions that primarily use math symbols in the multiple choice block where this issue is easily reproduced: http://www.problem-attic.com/account/documents/gAVHkt50erHmORfQH38/nodes/77501

_Copied from original issue: educaide/hachiko#456_

**Comment by Reinmar** [comment]
I cannot reproduce this on the staging server while I'm able to reproduce it on the production server. I remember fixing related issues in the plugin when porting it, so I guess I succeeded.

**Comment by gcortright** [comment]
@Reinmar some of these issues were ported from testing on production. They were to have been verified as still happening after the upgrade. Looks like we miss-categorized this one. Sorry!
