### ISSUE TITLE
Problem editor: Inclusion of '¢' character in table causes document export and pdf generation failure

### ISSUE THREAD

**Issue by gzip-pa** [educaide/ckeditor-dev#28]
_From @gzip-pa on June 25, 2015 17:25_

Write a new problem or edit an existing one
Create a table
 in one of the cells insert a '¢' symbol ( found under Σ,  Insert Specials >Special Characters> Misc. )
Save the problem. 
    None of your changes to the problem are displayed in the Problem Thumbnail, or you'll see only the thumbnail file name for a new problem.
Click 'Preview'
     An error occurred while trying to complete your last request.
Try to export as Slideshow
     Export Failed - We're sorry, there was a problem completing your export. Please contact support if this problem persists.

Reproducible in both Production and on staging

_Copied from original issue: educaide/hachiko#454_

**Comment by patrickdavey** [comment]
I have looked into this one.  The thumbnail job itself is failing, as far as I can tell the unicode char itself is being inserted into the tex (see below) and that is causing pdftex to fall over.  This is only an issue as @gzip-pa pointed out, when it is inside a table.

If I change this line: https://github.com/educaide/hachiko/blob/098f3f4e54bc4f22fa5b765839967de5a15ffc08/app/helpers/problem_helper.rb#L517 to read
`"#162" => "\\cent",` then the job succeeds, but the actual char is not printed.

I note that if you put a char _before_ the ¢‌ then it is fine.  

I will check in with you tomorrow about this @gcortright as I'm not entirely sure what is the correct behaviour here, one perhaps to run past Dan.

tex copied in here as I can't attach:


```
\input thumbs.sty
\begindocument
\beginproblem
¢ this is OK - outside a table


\table[
cols={l,l,l},
border=none,pos=left,vrule=none,hrule=none,headerfontstyle=normal,header=none,headerfontstep=0]{
  & 
			¢& 
			& 
			\cr
  & 
			& 
			& 
			\cr
  & 
			& 
			& 
			\cr
}

~
\endproblem
\enddocument
```

and the log

```
This is pdfTeX, Version 3.1415926-2.4-1.40.13 (TeX Live 2012) (format=acc4-pdf 2015.8.13)  10 SEP 2015 03:14
entering extended mode
 %&-line parsing enabled.
**/tmp/d20150910-6712-1ame5e0/4271653-2015-09-10T03-14-27Z.tex
(/tmp/d20150910-6712-1ame5e0/4271653-2015-09-10T03-14-27Z.tex (/home/rails/texm
f-eas/tex/educaide/thumbs.sty
version 4.3.10, format version 4.4.220
)
\openout0 = `4271653-2015-09-10T03-14-27Z.CSV'.

! Missing \cr inserted.
<inserted text> 
                \cr 
<to be read again> 
                   }
...
l.22 }
      
I'm guessing that you meant to end an alignment here.

! Misplaced \cr.
<inserted text> \cr 
                    
<to be read again> 
                   }
...
l.22 }
      
I can't figure out why you would want to use a tab mark
or \cr or \span just now. If something like a right brace
up above has ended a previous alignment prematurely,
you're probably due for more error messages, and you
might try typing `S' now just to see what is salvageable.

I'm guessing that you meant to end an alignment here.

.... REPEATS 100 TIMES... 
      
(That makes 100 errors; please try again.)
!  ==> Fatal error occurred, no output PDF file produced!
```

**Comment by patrickdavey** [comment]
Assigning to you @gcortright for comment.

**Comment by gcortright** [comment]
@patrickdavey This is certainly TeX issue. Will have to be addressed by Dan

**Comment by patrickdavey** [comment]
Well I'm not exactly sure, as if we alter the tex (that we are generating) that is passed to pdftex then it works out... so maybe we should be altering the tex in the app to escape / alter / whatever the cent char.  Anyway.. happy to be passed to Dan for comment anyway :)

**Comment by gcortright** [comment]
@patrickdavey Dan confirms that it is. It is only an issue in the table because of how TeX does expansions in tables. It can't parse the expansion it needs to when the first character is the cent character, which is why putting another character in front of it solves the problem.

**Comment by patrickdavey** [comment]
woohoo! Dan to the rescue :)
