### ISSUE TITLE
The "X" at the upper-left corner of the editor window does not close the editor

### ISSUE THREAD

**Issue by gzip-pa** [educaide/ckeditor-dev#3]
Steps to reproduce:
Log into PA and navigate to the Play Area
Choose a question bank
Click "Edit" on a problem to launch the editor
Click the "X" in the black circle at the upper-left corner of the editor window.
Result: The editor window remains open.

**Comment by Reinmar** [comment]
The same as here: https://github.com/educaide/ckeditor-dev/issues/1#issuecomment-129925819

**Comment by gzip-pa** [comment]
fixed
