### ISSUE TITLE
Problem Editor: Functionality of Word Style feature unclear: what you see is not what you get .

### ISSUE THREAD

**Issue by gzip-pa** [educaide/ckeditor-dev#30]
_From @gzip-pa on June 24, 2015 22:14_

Edit a problem
Select some text
select the 'W' (Word Style) from the toolbar.
Select "Emphasis"
The selection receives a dotted underline
Make another text selection and use Word Style to denote it as "Vocab"
It receives a dashed underline.
Result:
In the thumbnail and in Print Preview,  the Vocab has a solid underline and the Emphasis is Italicized.
It isn't intuitive that formatted text won't be denoted by dashed and dotted underlines in the exported documents. The Bold and Underline features function correctly, so this tool as it currently functions is not needed. In addition, the bold and italic tools do not work to remove apparent bold and italic formatting set with the Word Style tool, potentially frustrating users.

_Copied from original issue: educaide/hachiko#448_

**Comment by patrickdavey** [comment]
So, to confirm, the "word style" should be removed from ckeditor?

**Comment by gcortright** [comment]
@patrickdavey Honestly, not sure. I will have to inquire. It certainly does sound like the wordstyle plugin is not necessary.

**Comment by gcortright** [comment]
@patrickdavey I have now confirmed that the behavior described is correct. Different states and standards handle style `emphasis` and `vocab` differently. Consequently, the editor marks `emphasis` and `vocab` elements generically, and leaves the specific styling of those elements up to the TeX format file. All that is to say that WordStyle is working as expected. Closing this issue.
