### ISSUE TITLE
Problem Editor: reported size of image set in XFigure is 10x larger than actual size

### ISSUE THREAD

**Issue by gzip-pa** [educaide/ckeditor-dev#31]
_From @gzip-pa on June 24, 2015 18:4_

Edit a problem
Select the XFigure tab
Browse for an Image
Note the print size shown for the selected image. In my test case my image is 4.17in x 4.17in
Add the image.
Result: the reported size of the image displayed in XFigure is 41.67 in  x 41.67 in, or 10x the actual size.

_Copied from original issue: educaide/hachiko#445_

**Comment by patrickdavey** [comment]
@gcortright  I had a play with this one today too, and I'm wondering what is actually the best thing to do here.  The dpi information is clearly incorrect (see [Marks discussion in slack about it](https://resolvedigital.slack.com/archives/client-problem-attic/p1439432354000268) ), however, I'm not really sure what value it's giving the client to actually tell them, seeing as tex will, to some extent, do whatever it likes to make the image fit correctly on the page.  Certainly the DPI's as reported in the `figures` table are incorrect, but I don't think that these are actually passed to tex anyway.

I'll discuss it with you further tomorrow.  I did create a 96px * 96px image and play with different DPIs and layouts to see what tex did with it, and it certainly looks like it tries to respect the DPI encoded in the image where possible.

**Comment by patrickdavey** [comment]
I'd like to discuss this one.  We're obviously not reporting the correct DPI to the user and that could be fixed up.  At the moment (with the above merged fix) we do at least show the user the _same_ consistent values... however, the whole concept of how large the image will be on print is a bit moot as tex which force things to fit if it can anyway.

Note, I was able to force an exception in the tex by giving it 92px wide image with a DPI of 1.... not really an issue of course, but it's there (causes the job to crash out as the image is too big for the canvas, unsurprisingly)
