### ISSUE TITLE
None of the text formatting options in the toolbar are functional

### ISSUE THREAD

**Issue by gzip-pa** [educaide/ckeditor-dev#4]
Steps to reproduce:
Open a problem that contains plain text for editing.
Select some text, then click one of the formatting buttons in the toolbar, such as "B" for boldface, "I" for Italic, Underline, Subtext, Supertext, Word Style or Font Size.
None of these has any effect on the text, neither what is visible in the Editor nor in the problem thumbnail after the problem is saved.

**Comment by Reinmar** [comment]
The same as here: https://github.com/educaide/ckeditor-dev/issues/1#issuecomment-129925819

**Comment by gzip-pa** [comment]
fixed
