### ISSUE TITLE
Backspace behavior in mathquill span

### ISSUE THREAD

**Issue by gcortright** [educaide/ckeditor-dev#43]
I'm not sure if this is a problem that can be solved from the widget, or if an improvement in mathquill itself  is called for, but backspace behaves strangely when used in the mathquill  text area. I think what is happening is that the editor isn't allowing mathquill to handle backspaces when a mathquill text area is open. If focus is in the mathquill text area, then backspace should remove only what is in the text area, and not remove anything outside of the text area, or the text area itself.

To reproduce:

- start mathquill span and type some text or tex code
- without moving your cursor, immediately after typing in the text area click backspace a few times
- observe that your mathquill text area/span gets moved up lines in the editor, sometimes the rest of the content in the body of the editor gets removed, and sometimes even the browsers back function gets triggered.

Ultimately, backspace in the editor should affect only what is inside the mathquill text area when it has focus.

**Comment by mlewand** [comment]
I've been unable to remove anything outside the widget while pressing backspace inside the MathQuill edit mode. I've created a [video](https://drive.google.com/file/d/0B0mTGJYvT-wwY2FKVU9NRlpSRlE/view?usp=sharing) for that. Can I ask you to provide the browser name, and step-by-step issue description?

**Comment by gcortright** [comment]
@mlewand From your video it appears that you're trying to reproduce it in your dev environment. I would suggest that you try to reproduce it in your account on our staging server: www.staging.problem-attic.com

It is clearly reproducible (in Chrome) there by performing the steps outlined in my original issue.

**Comment by mlewand** [comment]
After some mailing we found out that this happens only if the math equation widget is the only one in a block, e.g. in a new, empty paragraph at the end of the content. :)

**Comment by mlewand** [comment]
PR #50 fixes this issue.
