### ISSUE TITLE
Disable drag & drop for mathquill text area?

### ISSUE THREAD

**Issue by gcortright** [educaide/ckeditor-dev#44]
While it is really cool that widgets can be natively dragged and dropped, we would not like mathquill text areas to be able to be dragged & dropped. Is there a way to disable drag & drop for the mathquill widget? After reading the documentation, it wasn't immediately apparent to me that there was a way to disable drag & drop.

**Comment by mlewand** [comment]
Luckily disabling drag support is quite simple, you can use [`widgetDefinition.draggable`](http://docs.ckeditor.com/#!/api/CKEDITOR.plugins.widget.definition-property-draggable) property to disable it. It's proposed in `ticket-44` branch.
