### ISSUE TITLE
Editor "Undo" button has no effect

### ISSUE THREAD

**Issue by gzip-pa** [educaide/ckeditor-dev#5]
Steps to reproduce:
Log into PA account and navigate to the Play Area
Choose a question bank
Click "Edit" on a problem 
Make some changes to the problem text.
Click the left-pointing curved "Undo"  arrow at the left side of the editor toolbar.
Result - your changes are not undone, as expected. (the keyboard command ^z, however, does work).
The "redo" button cannot be tested at this time because its active state depends on an "Undo" action being completed.

**Comment by Reinmar** [comment]
The same as here: https://github.com/educaide/ckeditor-dev/issues/1#issuecomment-129925819

**Comment by gzip-pa** [comment]
fixed
