### ISSUE TITLE
"Stem" and "Answer" editor window areas are half the height they should be

### ISSUE THREAD

**Issue by gzip-pa** [educaide/ckeditor-dev#7]
Steps to reproduce:
Log into PA account and navigate to Play Area
Choose a question bank
Click "Edit" on a problem
The issue is most apparent with problems with a lot of content
The size of the area where you can enter content takes up only the top half of the space available in the editor lightbox area. The  corresponding area in production takes advantage of the all of the available space, requiring less scrolling on part of the user.
![half-screen-staging](https://cloud.githubusercontent.com/assets/12751439/9048457/47ac66f0-39ee-11e5-8f99-d6f456c4efe3.png)

**Comment by Reinmar** [comment]
The `config.height` option isn't defined.

**Comment by Reinmar** [comment]
I was hesitating whether I can fix this issue by adding a rule to easconfig.js but as I noticed here: https://github.com/educaide/ckeditor-dev/issues/12#issuecomment-131106647 you don't use this file.

**Comment by gzip-pa** [comment]
fixed

**Comment by Reinmar** [comment]
Seem to be the issue again – #39.
